handle blockscout 404 error
immutable/ts-immutable-sdk pull request #1325
Opened 2024-01-09 04:00 UTC by ZacharyCouchman

# Summary

[WT-2028](https://immutable.atlassian.net/browse/WT-2028)
Fixing a case when blockscout does not find the wallet address balances (404) and handling that properly in the widgets to not go to the error view but to show no tokens found.

## Changed
How the Axios response is process in the HttpClient in Checkout

2024-01-09 05:31 UTC, andrearampin submitted a review, later dismissed

2024-01-10 00:24 UTC, andrearampin requested changes

2024-01-10 00:24 UTC, andrearampin commented on packages/checkout/sdk/test/__mocks__/window.ts
> +// global.navigator = dom.window.navigator;
Please remove this

2024-01-10 00:35 UTC, dreamoftrees approved these changes
Nice work @ZacharyCouchman 👍

2024-01-10 00:43 UTC, andrearampin approved these changes

2024-01-10 00:43 UTC, merged