Feature/sale widget payment method event
immutable/ts-immutable-sdk pull request #1358
Opened 2024-01-16 03:58 UTC by mimi-imtbl

# Summary
Exposing the chosen payment method through events.

2024-01-16 04:06 UTC, jwhardwick approved these changes

2024-01-16 21:45 UTC, jhesgodi approved these changes

2024-01-16 21:47 UTC, jhesgodi requested changes
@mimi-imtbl Adding the selected payment method is a great addition, however What I was originally suggesting was  to include the paymentMethod field on the success/failure events. 

Thoughts?

Also, for the current implementation please include sending this event thru segment analytics

2024-01-17 01:44 UTC, jhesgodi submitted a review, later dismissed
LGTM, thank you 🔥

2024-01-17 02:17 UTC, jwhardwick approved these changes

2024-01-17 02:40 UTC, CodeSchwert approved these changes

2024-01-17 02:45 UTC, dreamoftrees approved these changes
👍 Noice!

2024-01-17 02:45 UTC, merged