[feat] gpr 536 smart checkout override balance requirement on sufficient
immutable/ts-immutable-sdk pull request #1702
Opened 2024-04-26 06:28 UTC by mimi-imtbl

### Hi👋, please prefix this PR's title with:

- [ ] `breaking-change:` if you have introduced modification that necessitates immediate adjustments by this SDK's users to their applications, clients, or integrations to avert disruptions to existing features or functionalities.
- [ ] `feat:`, `fix:`, `refactor:`, `docs:`, or `chore:`.

# Summary

Add `overrideSufficientBalanceCheckResult` to get funding routes on `sufficient`.

2024-04-26 07:16 UTC, jhesgodi requested changes
~Thanks @mimi-imtbl  upon checking I have a concern about the current approach.~

~The override strategy intends to force an "insufficient" result, to trick the routing calculator logic to generate funding routes.~

~This will mislead users relying on the actual sufficient SMC result.~

~Instead, we should decouple funding routes from the balance check, allowing them to be independent results irrespective of the initial balance status.~

~This shift ensures SMC can now provide accurate balance check, and all alternative possible paths.~

2024-04-28 23:55 UTC, jhesgodi submitted a review, later dismissed
👍🏾

2024-04-29 02:57 UTC, jhesgodi approved these changes

2024-04-29 03:10 UTC, dreamoftrees approved these changes
👍 Nice work @mimi-imtbl

2024-04-29 03:36 UTC, merged