[feat] cm 632 sale widget waitFulfillmentSettlements
immutable/ts-immutable-sdk pull request #1753
Opened 2024-05-09 03:46 UTC by mimi-imtbl

### Hi👋, please prefix this PR's title with:

- [ ] `breaking-change:` if you have introduced modification that necessitates immediate adjustments by this SDK's users to their applications, clients, or integrations to avert disruptions to existing features or functionalities.
- [ ] `feat:`, `fix:`, `refactor:`, `docs:`, or `chore:`.

## Added 

Added `waitFulfillmentSettlements` to sale widget config to enable/disable wait for transaction settlement.

2024-05-09 04:21 UTC, jwhardwick submitted a review, later dismissed

2024-05-09 10:44 UTC, jhesgodi commented on packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
> +                  waitFulfillmentSettlements={
Question and suggestion?
I think we may want the wait to be enabled by default, right? If so then I suggest you use
```
waitFulfillmentSettlements={this.properties?.config?.waitFulfillmentSettlements ?? true}
```
this expresion will allow`false`, but if null or undefined will default to `true`

2024-05-09 10:45 UTC, jhesgodi commented on packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
> +  waitFulfillmentSettlements: false,
default to `true`

2024-05-09 10:45 UTC, jhesgodi requested changes
Looks good, left comment re initial state

2024-05-09 23:43 UTC, mimi-imtbl commented on packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
> +  waitFulfillmentSettlements: false,
good catch @J

2024-05-10 00:24 UTC, jwhardwick approved these changes

2024-05-10 03:32 UTC, jhesgodi approved these changes

2024-05-10 04:14 UTC, merged