fix: ID-1732 Fix background blur and append required font links to the head
immutable/ts-immutable-sdk pull request #1797
Opened 2024-05-17 03:13 UTC by imx-mikhala

### Hi👋, please prefix this PR's title with:

- [ ] `breaking-change:` if you have introduced modification that necessitates immediate adjustments by this SDK's users to their applications, clients, or integrations to avert disruptions to existing features or functionalities.
- [ ] `feat:`, `fix:`, `refactor:`, `docs:`, or `chore:`.

# Summary

# Detail and impact of the change

## Added 

## Changed

## Deprecated

## Removed

## Fixed

## Security

# Anything else worth calling out?

2024-05-17 03:14 UTC, imx-mikhala commented on packages/passport/sdk/src/overlay/overlay.ts
> +      document.head.appendChild(link3);
this is all the links from the [stackblitz](https://stackblitz.com/edit/stackblitz-starters-tcunqf?file=index.html)

2024-05-17 03:56 UTC, oliyoung submitted a review, later dismissed

2024-05-17 06:26 UTC, haydenfowler requested changes
The link elements are added to the head element each time the overlay is displayed.
Also, is a `preconnect` link accurate here if we're only adding the link at the time that the fonts are needed?

2024-05-17 06:28 UTC, imx-mikhala commented
> The link elements are added to the head element each time the overlay is displayed. Also, is a `preconnect` link accurate here if we're only adding the link at the time that the fonts are needed?

oh good catch i will patch that. not sure re the `preconnect`, if its not required i can remove

2024-05-20 04:20 UTC, haydenfowler approved these changes

2024-05-20 04:26 UTC, yundifu approved these changes

2024-05-20 04:38 UTC, merged