[GMS-2129] Update code examples for blockchain data package
immutable/ts-immutable-sdk pull request #2181
Opened 2024-09-17 04:26 UTC by allan-almeida-imtbl

### Hi👋, please prefix this PR's title with:

- [ ] `breaking-change:` if you have introduced modification that necessitates immediate adjustments by this SDK's users to their applications, clients, or integrations to avert disruptions to existing features or functionalities.
- [ ] `feat:`, `fix:`, `refactor:`, `docs:`, or `chore:`.

# Summary

# Detail and impact of the change

## Added 

## Changed

## Deprecated

## Removed

## Fixed

## Security

# Anything else worth calling out?

2024-09-17 04:36 UTC, allan-almeida-imtbl commented on examples/blockchain-data/package.json
> +    "@imtbl/sdk": "^1.52.1"
TODO shoould be `'latest'`

2024-09-18 06:10 UTC, zaidarain1 requested changes

2024-09-18 06:10 UTC, zaidarain1 commented on examples/blockchain-data/README.md
Could this README be updated to add some additional info regarding what the example is for/what it shows? Things such as the main functionality it is intended to showcase would be a good base. There are a fair amount of READMEs in other examples, such as the orderbook or passport ones that might also give some ideas 😄

2024-09-18 23:57 UTC, allan-almeida-imtbl commented on examples/blockchain-data/README.md
no worries @zaidarain1 , updated

2024-09-19 00:00 UTC, zaidarain1 approved these changes

2024-09-19 00:37 UTC, merged