docs: Add bid creation example applications
immutable/ts-immutable-sdk pull request #2201
Opened 2024-09-23 01:04 UTC by lfportal

### Hi👋, please prefix this PR's title with:

- [ ] `breaking-change:` if you have introduced modification that necessitates immediate adjustments by this SDK's users to their applications, clients, or integrations to avert disruptions to existing features or functionalities.
- [x] `feat:`, `fix:`, `refactor:`, `docs:`, or `chore:`.

# Summary

Add example applications for orderbook bids feature.

2024-09-23 02:09 UTC, lfportal commented on examples/orderbook/create-bid-with-nextjs/package.json
> +    "@imtbl/sdk": "1.53.0-alpha.11",
**TODO:** Return to `@latest` before merging.

2024-09-23 03:58 UTC, lfportal commented on examples/orderbook/fulfill-bid-with-nextjs/package.json
> +    "@imtbl/sdk": "1.53.0-alpha.11",
**TODO:** Return to `@latest` before merging.

2024-09-25 05:14 UTC, naveen-imtb approved these changes

2024-09-25 05:22 UTC, zaidarain1 requested changes

2024-09-25 05:22 UTC, zaidarain1 commented on examples/orderbook/create-bid-with-nextjs/app/utils/bid.ts
> +import { Web3Provider } from "@ethersproject/providers";
`@ethersproject/providers` is missing from the dependencies object in the package.json of this example. Could that please be added there?

2024-09-25 05:22 UTC, zaidarain1 commented on examples/orderbook/create-bid-with-nextjs/playwright.config.ts
> +    workers: process.env.CI ? 1 : undefined,
The playwright config base used for examples was recently updated to work a bit better on CI. The changes made were:
`workers: "80%"`,
and
`webServer.command: "yarn start"`

Could those changes be applied to this PR?

2024-09-25 05:22 UTC, zaidarain1 commented on examples/orderbook/fulfill-bid-with-nextjs/playwright.config.ts
> +    workers: process.env.CI ? 1 : undefined,
As mentioned earlier regarding `workers` and `webServer.command`

2024-09-25 05:40 UTC, zaidarain1 submitted a review, later dismissed

2024-09-25 06:25 UTC, zaidarain1 approved these changes

2024-09-25 06:51 UTC, merged