TD1712 Add collection bid creation example app
immutable/ts-immutable-sdk pull request #2241
Opened 2024-09-27 04:30 UTC by frankisawesome

### Hi👋, please prefix this PR's title with:

- [ ] `breaking-change:` if you have introduced modification that necessitates immediate adjustments by this SDK's users to their applications, clients, or integrations to avert disruptions to existing features or functionalities.
- [ ] `feat:`, `fix:`, `refactor:`, `docs:`, or `chore:`.

# Summary

# Detail and impact of the change

## Added 

## Changed

## Deprecated

## Removed

## Fixed

## Security

# Anything else worth calling out?

2024-10-09 01:23 UTC, Sam-Jeston approved these changes
This changeset, while large, is isolated to new sample apps in `examples/` and a patch to the func-tests to use the provided allowlist. No SDK code change is included here

2024-10-09 01:45 UTC, zaidarain1 requested changes

2024-10-09 01:45 UTC, zaidarain1 commented on examples/orderbook/fulfill-collection-bid-with-nextjs/README.md
Could you give this README a small update to provide a brief overview of the example, similar to other examples? Something small like a few sentences should be enough 😄

2024-10-09 01:45 UTC, zaidarain1 commented on examples/orderbook/fulfill-collection-bid-with-nextjs/package.json
> +  "name": "fulfill-collection-bid-with-nextjs",
Could you prepend the `@examples/` to the name

2024-10-09 01:45 UTC, zaidarain1 commented on examples/orderbook/fulfill-collection-bid-with-nextjs/package.json
> +    "tailwindcss": "^3.4.1",
Tailwind doesn't seem to be used at all in this example. Is it safe to be removed, along with the tailwind config file? Is postcss still needed for biom3/react or any other purpose if tailwind isn't present? If not, that could be cleaned up too, along with its config file

2024-10-09 06:46 UTC, zaidarain1 approved these changes

2024-10-09 07:04 UTC, Sam-Jeston submitted a review, later dismissed

2024-10-10 04:22 UTC, CodeSchwert approved these changes

2024-10-10 04:30 UTC, Sam-Jeston approved these changes

2024-10-10 23:56 UTC, merged