feat: Add IMX wrapping to the Checkout SDK
immutable/ts-immutable-sdk pull request #2315
Opened 2024-10-16 04:50 UTC by luads

# Summary

This method introduces a way for wrapping IMX into wIMX and the other way around.

# Detail and impact of the change

## Added 

## Changed

## Deprecated

## Removed

## Fixed

## Security

# Anything else worth calling out?

2024-10-16 04:55 UTC, alejoloaiza approved these changes

2024-10-16 05:30 UTC, alejoloaiza approved these changes

2024-10-16 05:50 UTC, jwhardwick reviewed
Looks good @luads .

Thoughts on making `getUnsignedWrapUnwrapTx` public and creating an `Exchange` instance to use it? https://github.com/immutable/ts-immutable-sdk/blob/7067a430908813c77fd0c8070e97fea571f39846/packages/internal/dex/sdk/src/exchange.ts#L211

Benefit is having this logic live in one place, and that code already handles fee quotes.

2024-10-29 09:50 UTC, alejoloaiza requested changes
Not needed anymore

2024-11-04 05:16 UTC, closed without merging